# Python CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
        environment:
          PIPENV_VENV_IN_PROJECT: 1
          PIPENV_QUIET: 1
          CODECOV_TOKEN: "18a8804c-6d8e-4b9b-a357-d7a8bae9ac44"
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade --quiet pip
            pip install --quiet pipenv
            pipenv install --dev --deploy

      - save_cache:
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}
          paths:
            - ./venv

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest

      - run:
          name: run linter
          command: |
            . venv/bin/activate
            flake8 .
